# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # config.vm.box = "maxx/ubuntu16"
  config.vm.box = "hashicorp/precise64"
  config.vm.provider "hyperv"
  config.vm.box_check_update = true
  config.vm.boot_timeout = 120
 
  # ssh seems to work better than winssh
  config.vm.communicator = "ssh"

  # The bridge name must match the one in Hyper-V Manager's Virtual Switch Manager
  config.vm.network "public_network", type: "dhcp", bridge: "Wired Ethernet"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Share folders to the guest VM.
  # The first argument is the path on the host to the actual folder.
  # The second argument is the path on the guest to mount the folder.
  config.vm.synced_folder ".", "/vagrant",
      type: "rsync",
      disabled: false

  config.vm.provider "hyperv" do |hv|
    hv.cpus = 2
    hv.memory = 2048
    hv.ip_address_timeout = 90
    # This setting requires Windows 10
    # hv.enable_virtualization_extensions = true
    hv.differencing_disk = true
    # Name in Hyper-V manager GUI
    hv.vmname = "ubuntu-vagrant-64"
  end

  # Enable provisioning with a shell script.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y -q software-properties-common python-software-properties
    sudo add-apt-repository -y ppa:webupd8team/java
    sudo add-apt-repository -y ppa:openjdk-r/ppa
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install -y -q git
    sudo apt-get install -y -q xrdp
    # sudo apt-get install -y -q openjdk-7-jdk
    # sudo apt-get install -y -q openjdk-8-jdk
    sudo apt-get install -y -q oracle-java8-installer
    sudo apt-get install -y -q oracle-java8-set-default
  SHELL
end
